### ISSUE TITLE
Kubernetes module getting error 

### ISSUE THREAD

**Issue by smartlizzard** [tensult/terraform#27]
I am getting error during terraform plan. It gives nat-gateway and eks subnet error. Can you please help me ?

on network\vpc.tf line 121, in resource "aws_nat_gateway" "nat-gw":
 121:   subnet_id     = "${element(aws_subnet.master_subnet.*.id, count.index)}"

The "count" object can be used only in "resource" and "data" blocks, and only
when the "count" argument is set.

**Comment by koladilip** [comment]
Please git pull again try.

**Comment by smartlizzard** [comment]
Hi Dilip,
I am new to terraform as well as eks, so I tring to learn from here. I am getting below error.

Error: Incorrect attribute value type

  on cluster\eks-cluster.tf line 83, in resource "aws_eks_cluster" "eks-cluster":
  83:     subnet_ids         = ["${var.subnet_ids}"]

Inappropriate value for attribute "subnet_ids": element 0: string required.

**Comment by koladilip** [comment]
Looks like the issue is in input params. Please put your params by replacing them with dummy values. (DONT PUT ACTUAL AWS VALUES HERE)

**Comment by koladilip** [comment]
No response so closing
