### ISSUE TITLE
Error: Incorrect attribute value type and bunch of Warnings

### ISSUE THREAD

**Issue by linecolumn** [tensult/terraform#31]
Trying to play with the Kubernetes TF files but I'm stuck with following:

```
Error: Incorrect attribute value type

  on cluster/eks-cluster.tf line 83, in resource "aws_eks_cluster" "eks-cluster":
  83:     subnet_ids         = "${var.subnet_ids}"

Inappropriate value for attribute "subnet_ids": incorrect set element type:
string required.
```
cluster/variable.tf tried with following:

```variable "subnet_ids" {
  type        = "list"
  description = "List of all subnet in cluster"
  default = ["vpc-05186c774a220XXXX"]
}
```
and

```variable "subnet_ids" {
  type        = "list"
  description = "List of all subnet in cluster"
  default = []
}
```

Terraform v0.12.16
+ provider.aws v2.40.0
+ provider.http v1.1.1

Can't pass this thing...

**Comment by koladilip** [comment]
This is based on terraform 0.11

Thanks,
Dilip
Tensult
________________________________

**Comment by shaikhvazid** [comment]
This issue occurs because of using different terraform version. Please use terraform version 0.11.14.
Hence we are closing this issue. 

Regards,
Vazid
Tensult
