### ISSUE TITLE
Bunch of warnings

### ISSUE THREAD

**Issue by linecolumn** [tensult/terraform#32]
Probably due latest terraform (v0.12.16), bunch of warnings are happening with same explanation:

```Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

Warning: Interpolation-only expressions are deprecated

  on main.tf line 2, in provider "aws":
   2:   region  = "${var.region}"

  on main.tf line 3, in provider "aws":
   3:   profile = "${var.profile}"

  on cluster/alb.tf line 3, in resource "aws_security_group" "eks_alb_sg":
   3:   vpc_id      = "${var.vpc_id}"

  on cluster/alb.tf line 23, in resource "aws_security_group_rule" "allow_http":
  23:   security_group_id        = "${aws_security_group.eks_alb_sg.id}"

  on cluster/alb.tf line 24, in resource "aws_security_group_rule" "allow_http":
  24:   source_security_group_id = "${aws_security_group.worker-node-sg.id}"

[...]

  on network/vpc.tf line 154, in resource "aws_route_table_association" "private_sub":
 154:   route_table_id = "${aws_route_table.rt_private.id}"

**Comment by koladilip** [comment]
This is based on terraform 0.11, Please try with that version

**Comment by shaikhvazid** [comment]
Please use terraform version 0.11.14.

We are closing this issue. 

Regards,
Vazid 
Tensult
